version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - db
  worker:
    build: .
    command: celery -B -A fancy_dashboard worker -l info
    depends_on:
      - db
      - redis
  db:
    image: postgres
  redis:
    image: redis
